# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1SP', 'seat_positions': [1, 2]},
    bid='2N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'game_forcing_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 13,
                   'weight': 60}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['context_initiating', 'forcing'],
     'action_type': 'jacoby_2n',
     'target_suit': 'S',
     'forcing_status': 'game_forcing',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'jacoby_2n'},
     {'key': 'forcing_status', 'status': 'game_forcing'}],
    description='Jacoby 2N game-forcing spade raise declaration.',
    system_notes='After 1S, 2N is Jacoby 2N, game forcing with four-card support.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '1HP', 'seat_positions': [1, 2]},
    bid='2N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'game_forcing_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 13,
                   'weight': 60}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['context_initiating', 'forcing'],
     'action_type': 'jacoby_2n',
     'target_suit': 'H',
     'forcing_status': 'game_forcing',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'jacoby_2n'},
     {'key': 'forcing_status', 'status': 'game_forcing'}],
    description='Jacoby 2N game-forcing heart raise declaration.',
    system_notes='After 1H, 2N is Jacoby 2N, game forcing with four-card support.',
)
