# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='4H',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'six_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 6,
                   'weight': 60},
                  {'criterion_id': 'game_forcing_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 10,
                   'weight': 70}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['directive', 'context_initiating', 'forcing'],
     'action_type': 'texas_transfer',
     'target_suit': 'S',
     'alertable': True},
    effects=[{'key': 'texas_transfer', 'target_suit': 'S', 'status': 'pending'}],
    description='Responder bids 4H as Texas transfer to spades.',
    system_notes='After 1N, 4H is Texas transfer to spades.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '1NP4HP', 'seat_positions': [1, 2, 3, 4]},
    bid='4S',
    requires={'state_exists': {'key': 'texas_transfer', 'target_suit': 'S', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_texas_spades',
                   'evaluator': 'state_exists',
                   'query': {'key': 'texas_transfer', 'target_suit': 'S', 'status': 'pending'},
                   'weight': 100}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'texas_completion',
     'target_suit': 'S',
     'alertable': False},
    effects=[{'key': 'texas_transfer', 'target_suit': 'S', 'status': 'completed'},
     {'key': 'agreed_suit', 'suit': 'S', 'source': 'texas_transfer'}],
    description='Opener completes the Texas transfer to spades.',
    system_notes='After 1N-4H, 4S completes the Texas transfer.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='4D',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 60},
                  {'criterion_id': 'game_forcing_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 10,
                   'weight': 70}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['directive', 'context_initiating', 'forcing'],
     'action_type': 'texas_transfer',
     'target_suit': 'H',
     'alertable': True},
    effects=[{'key': 'texas_transfer', 'target_suit': 'H', 'status': 'pending'}],
    description='Responder bids 4D as Texas transfer to hearts.',
    system_notes='After 1N, 4D is Texas transfer to hearts.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '1NP4DP', 'seat_positions': [1, 2, 3, 4]},
    bid='4H',
    requires={'state_exists': {'key': 'texas_transfer', 'target_suit': 'H', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_texas_hearts',
                   'evaluator': 'state_exists',
                   'query': {'key': 'texas_transfer', 'target_suit': 'H', 'status': 'pending'},
                   'weight': 100}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'texas_completion',
     'target_suit': 'H',
     'alertable': False},
    effects=[{'key': 'texas_transfer', 'target_suit': 'H', 'status': 'completed'},
     {'key': 'agreed_suit', 'suit': 'H', 'source': 'texas_transfer'}],
    description='Opener completes the Texas transfer to hearts.',
    system_notes='After 1N-4D, 4H completes the Texas transfer.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '1NP4DP4HP', 'seat_positions': [1, 2, 3, 4]},
    bid='P',
    requires={'state_exists': {'key': 'texas_transfer', 'target_suit': 'H', 'status': 'completed'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'texas_heart_game_completed',
                   'evaluator': 'state_exists',
                   'query': {'key': 'texas_transfer', 'target_suit': 'H', 'status': 'completed'},
                   'weight': 100}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['signoff', 'final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'H',
     'level': 4,
     'alertable': False},
    effects=[{'key': 'final_contract', 'target_suit': 'H', 'level': 4, 'source': 'texas_transfer'}],
    description='Responder passes after the Texas heart transfer is completed, placing 4H.',
    system_notes='After 1N-4D-4H, pass places the heart game unless responder has slam interest.',
)

Call(
    id='cs_6',
    context={'auction_pattern': '1NP4HP4SP', 'seat_positions': [1, 2, 3, 4]},
    bid='P',
    requires={'state_exists': {'key': 'texas_transfer', 'target_suit': 'S', 'status': 'completed'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'texas_spade_game_completed',
                   'evaluator': 'state_exists',
                   'query': {'key': 'texas_transfer', 'target_suit': 'S', 'status': 'completed'},
                   'weight': 100}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['signoff', 'final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'S',
     'level': 4,
     'alertable': False},
    effects=[{'key': 'final_contract', 'target_suit': 'S', 'level': 4, 'source': 'texas_transfer'}],
    description='Responder passes after the Texas spade transfer is completed, placing 4S.',
    system_notes='After 1N-4H-4S, pass places the spade game unless responder has slam interest.',
)
