# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='2D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'game_force_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 13,
                   'weight': 120},
                  {'criterion_id': 'five_card_club_support',
                   'evaluator': 'min_value',
                   'input': 'self.clubs',
                   'min': 5,
                   'weight': 80},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 30}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['support_showing', 'game_forcing', 'context_initiating'],
     'action_type': 'crisscross_minor_raise',
     'target_suit': 'C',
     'raise_strength': 'game_force',
     'alertable': True},
    effects=[{'key': 'minor_raise', 'target_suit': 'C', 'strength': 'game_force', 'method': 'crisscross'},
     {'key': 'agreed_suit', 'suit': 'C', 'source': 'crisscross'},
     {'key': 'forcing_status', 'status': 'game_forcing', 'target_suit': 'C'}],
    description='Crisscross raise 1C-2D: game-forcing club support, no four-card major.',
    system_notes='After 1C, 2D is a game-forcing crisscross raise showing clubs.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='3C',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'game_force_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 13,
                   'weight': 120},
                  {'criterion_id': 'four_card_diamond_support',
                   'evaluator': 'min_value',
                   'input': 'self.diamonds',
                   'min': 4,
                   'weight': 80},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 30}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['support_showing', 'game_forcing', 'context_initiating'],
     'action_type': 'crisscross_minor_raise',
     'target_suit': 'D',
     'raise_strength': 'game_force',
     'alertable': True},
    effects=[{'key': 'minor_raise', 'target_suit': 'D', 'strength': 'game_force', 'method': 'crisscross'},
     {'key': 'agreed_suit', 'suit': 'D', 'source': 'crisscross'},
     {'key': 'forcing_status', 'status': 'game_forcing', 'target_suit': 'D'}],
    description='Crisscross raise 1D-3C: game-forcing diamond support, no four-card major.',
    system_notes='After 1D, 3C is a game-forcing crisscross raise showing diamonds.',
)
