# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='5N',
    requires={'all': [{'state_exists': {'key': 'keycard_response',
                              'method': '1430',
                              'trump_suit': 'H',
                              'response': 'zero_or_three'}},
             {'not': {'state_exists': {'key': 'targeted_king_ask', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'heart_grand_try_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 18,
                   'weight': 110},
                  {'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 60},
                  {'criterion_id': 'asker_has_three_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'keycard_count', 'hand': 'self', 'trump_suit': 'H'},
                            'right': {'const': 3}},
                   'weight': 60}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry', 'honor_asking'],
     'action_type': 'targeted_king_ask',
     'target_suit': 'D',
     'target_rank': 'K',
     'trump_suit': 'H',
     'alertable': True},
    capabilities=['start_frame', 'specific_king_ask', 'slam_inquiry'],
    effects=[{'key': 'targeted_king_ask',
      'trump_suit': 'H',
      'target_suit': 'D',
      'rank': 'K',
      'status': 'pending'},
     {'key': 'all_keycards_known', 'trump_suit': 'H', 'status': 'yes'}],
    description='Asker bids 5N to ask specifically for the diamond king after a 1430 zero-or-three response.',
    system_notes='After 4N-5D in a heart RKCB auction, 5N asks whether partner holds the diamond king.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '*'},
    bid='6D',
    requires={'all': [{'state_exists': {'key': 'targeted_king_ask',
                              'trump_suit': 'H',
                              'target_suit': 'D',
                              'rank': 'K',
                              'status': 'pending'}},
             {'not': {'state_exists': {'key': 'targeted_king_response',
                                      'target_suit': 'D',
                                      'rank': 'K'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'has_diamond_king',
                   'evaluator': 'expression',
                   'expr': {'op': 'contains_rank', 'hand': 'self', 'suit': 'D', 'rank': 'K'},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response', 'control_showing'],
     'action_type': 'targeted_king_response',
     'target_suit': 'D',
     'target_rank': 'K',
     'alertable': True},
    capabilities=['answer_frame', 'specific_king_response'],
    effects=[{'key': 'targeted_king_response',
      'trump_suit': 'H',
      'target_suit': 'D',
      'rank': 'K',
      'status': 'yes'}],
    description='Responder bids 6D to show the diamond king over the targeted king ask.',
    system_notes='Over the targeted 5N ask, 6D shows the diamond king.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '*'},
    bid='7H',
    requires={'all': [{'state_exists': {'key': 'targeted_king_response',
                              'trump_suit': 'H',
                              'target_suit': 'D',
                              'rank': 'K',
                              'status': 'yes'}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'final_grand_strength',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 18,
                   'weight': 100},
                  {'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'H',
     'level': 7,
     'alertable': False},
    capabilities=['place_contract', 'slam_placement'],
    effects=[{'key': 'final_contract', 'target_suit': 'H', 'level': 7, 'source': 'targeted_king_ask'}],
    description='Asker places the heart grand slam after the diamond king is confirmed.',
    system_notes='7H is final placement after partner shows the diamond king in the heart-slam route.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '*'},
    bid='P',
    requires={'state_exists': {'key': 'final_contract', 'source': 'targeted_king_ask'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'final_contract_placed',
                   'evaluator': 'state_exists',
                   'query': {'key': 'final_contract', 'source': 'targeted_king_ask'},
                   'weight': 100}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['final_placement'],
     'action_type': 'pass_final_contract',
     'alertable': False},
    capabilities=['place_contract', 'pass_final_contract'],
    description='Partner passes after the targeted-king route places a final contract.',
    system_notes='After 7H is placed, partner passes to end the auction.',
)
