# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Evaluator(
    id='eval_weak_two_opening',
    description='Seat- and vulnerability-sensitive weak two opening evaluator.',
    evaluator_type='expression',
    definition={'op': 'and',
     'args': [{'op': 'gte',
               'left': {'op': 'length', 'hand': 'self', 'suit': {'param': 'target_suit'}},
               'right': {'const': 6}},
              {'op': 'lte', 'left': {'var': 'self.hcp'}, 'right': {'const': 10}},
              {'op': 'or',
               'args': [{'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 3}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 4}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 1}},
                                  {'op': 'eq',
                                   'left': {'var': 'env.vulnerability_relation'},
                                   'right': {'const': 'favorable'}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 5}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 1}},
                                  {'op': 'in',
                                   'left': {'var': 'env.vulnerability_relation'},
                                   'right': {'const': ['none', 'both']}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 6}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 1}},
                                  {'op': 'eq',
                                   'left': {'var': 'env.vulnerability_relation'},
                                   'right': {'const': 'unfavorable'}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 7}},
                                  {'op': 'or',
                                   'args': [{'op': 'gte',
                                             'left': {'op': 'honor_count',
                                                      'hand': 'self',
                                                      'suit': {'param': 'target_suit'},
                                                      'ranks': ['A', 'K', 'Q']},
                                             'right': {'const': 2}},
                                            {'op': 'gte',
                                             'left': {'op': 'honor_count',
                                                      'hand': 'self',
                                                      'suit': {'param': 'target_suit'},
                                                      'ranks': ['A', 'K', 'Q', 'J', 'T']},
                                             'right': {'const': 3}}]}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 2}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 7}},
                                  {'op': 'or',
                                   'args': [{'op': 'gte',
                                             'left': {'op': 'honor_count',
                                                      'hand': 'self',
                                                      'suit': {'param': 'target_suit'},
                                                      'ranks': ['A', 'K', 'Q']},
                                             'right': {'const': 2}},
                                            {'op': 'gte',
                                             'left': {'op': 'honor_count',
                                                      'hand': 'self',
                                                      'suit': {'param': 'target_suit'},
                                                      'ranks': ['A', 'K', 'Q', 'J', 'T']},
                                             'right': {'const': 3}}]}]}]}]},
)

Evaluator(
    id='eval_three_level_preempt',
    description='Seat- and vulnerability-sensitive natural three-level preempt evaluator.',
    evaluator_type='expression',
    definition={'op': 'and',
     'args': [{'op': 'gte',
               'left': {'op': 'length', 'hand': 'self', 'suit': {'param': 'target_suit'}},
               'right': {'const': 7}},
              {'op': 'lte', 'left': {'var': 'self.hcp'}, 'right': {'const': 10}},
              {'op': 'or',
               'args': [{'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 3}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 3}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 1}},
                                  {'op': 'eq',
                                   'left': {'var': 'env.vulnerability_relation'},
                                   'right': {'const': 'favorable'}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 4}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 1}},
                                  {'op': 'in',
                                   'left': {'var': 'env.vulnerability_relation'},
                                   'right': {'const': ['none', 'both']}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 5}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 1}},
                                  {'op': 'eq',
                                   'left': {'var': 'env.vulnerability_relation'},
                                   'right': {'const': 'unfavorable'}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 6}}]},
                        {'op': 'and',
                         'args': [{'op': 'eq',
                                   'left': {'var': 'env.seat_position'},
                                   'right': {'const': 2}},
                                  {'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 7}},
                                  {'op': 'or',
                                   'args': [{'op': 'gte',
                                             'left': {'op': 'honor_count',
                                                      'hand': 'self',
                                                      'suit': {'param': 'target_suit'},
                                                      'ranks': ['A', 'K', 'Q']},
                                             'right': {'const': 2}},
                                            {'op': 'gte',
                                             'left': {'op': 'honor_count',
                                                      'hand': 'self',
                                                      'suit': {'param': 'target_suit'},
                                                      'ranks': ['A', 'K', 'Q', 'J', 'T']},
                                             'right': {'const': 3}}]}]}]}]},
)
