# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='2D',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'five_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 5,
                   'weight': 70}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['directive', 'context_initiating', 'forcing'],
     'action_type': 'transfer',
     'target_suit': 'H',
     'alertable': True,
     'acbl_explanation': 'hearts'},
    effects=[{'key': 'transfer', 'target_suit': 'H', 'status': 'pending'}],
    description='Responder bids 2D as a transfer to hearts with at least five hearts.',
    system_notes='After 1N, 2D transfers to hearts.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='2H',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'five_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 5,
                   'weight': 70}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['directive', 'context_initiating', 'forcing'],
     'action_type': 'transfer',
     'target_suit': 'S',
     'alertable': True,
     'acbl_explanation': 'spades'},
    effects=[{'key': 'transfer', 'target_suit': 'S', 'status': 'pending'}],
    description='Responder bids 2H as a transfer to spades with at least five spades.',
    system_notes='After 1N, 2H transfers to spades.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '1NP2DP', 'seat_positions': [1, 2, 3, 4]},
    bid='2H',
    requires={'state_has': {'transfer': {'target_suit': 'H', 'status': 'pending'}}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_heart_transfer',
                   'evaluator': 'state_exists',
                   'query': {'key': 'transfer', 'target_suit': 'H', 'status': 'pending'},
                   'weight': 10}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'transfer_completion',
     'target_suit': 'H',
     'alertable': False},
    effects=[{'key': 'transfer_completion', 'target_suit': 'H', 'status': 'completed'}],
    description='Opener completes the heart transfer at 2H.',
    system_notes='After 1N-2D, 2H completes the heart transfer.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='2S',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'six_clubs',
                   'evaluator': 'min_value',
                   'input': 'self.clubs',
                   'min': 6,
                   'weight': 70}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['directive', 'context_initiating', 'forcing'],
     'action_type': 'transfer',
     'target_suit': 'C',
     'alertable': True},
    effects=[{'key': 'transfer', 'target_suit': 'C', 'status': 'pending'}],
    description='Responder bids 2S as a transfer to clubs with at least six clubs.',
    system_notes='After 1N, 2S transfers to clubs and requires a six-card club suit.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '1NP2SP', 'seat_positions': [1, 2, 3, 4]},
    bid='2N',
    requires={'state_exists': {'key': 'transfer', 'target_suit': 'C', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'honor_third_club_support',
                   'evaluator': 'named_evaluator',
                   'evaluator_id': 'eval_minor_honor_third',
                   'params': {'target_suit': 'C'},
                   'weight': 100}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'superaccept',
     'target_suit': 'C',
     'alertable': True},
    effects=[{'key': 'transfer_superaccept', 'target_suit': 'C', 'status': 'accepted'}],
    description='Opener bids the gap 2N to superaccept the club transfer with honor-third or stronger support.',
    system_notes='After 1N-2S, 2N is the gap superaccept for clubs.',
)

Call(
    id='cs_6',
    context={'auction_pattern': '1NP2SP', 'seat_positions': [1, 2, 3, 4]},
    bid='3C',
    requires={'state_exists': {'key': 'transfer', 'target_suit': 'C', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_club_transfer',
                   'evaluator': 'state_exists',
                   'query': {'key': 'transfer', 'target_suit': 'C', 'status': 'pending'},
                   'weight': 10}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'transfer_completion',
     'target_suit': 'C',
     'alertable': False},
    effects=[{'key': 'transfer_completion', 'target_suit': 'C', 'status': 'completed'}],
    description='Opener accepts the club transfer normally at 3C.',
    system_notes='After 1N-2S, 3C is the normal club transfer acceptance.',
)

Call(
    id='cs_7',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='2N',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'six_diamonds',
                   'evaluator': 'min_value',
                   'input': 'self.diamonds',
                   'min': 6,
                   'weight': 70}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['directive', 'context_initiating', 'forcing'],
     'action_type': 'transfer',
     'target_suit': 'D',
     'alertable': True},
    effects=[{'key': 'transfer', 'target_suit': 'D', 'status': 'pending'}],
    description='Responder bids 2N as a transfer to diamonds with at least six diamonds.',
    system_notes='After 1N, 2N transfers to diamonds and requires a six-card diamond suit.',
)

Call(
    id='cs_8',
    context={'auction_pattern': '1NP2NP', 'seat_positions': [1, 2, 3, 4]},
    bid='3C',
    requires={'state_exists': {'key': 'transfer', 'target_suit': 'D', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'honor_third_diamond_support',
                   'evaluator': 'named_evaluator',
                   'evaluator_id': 'eval_minor_honor_third',
                   'params': {'target_suit': 'D'},
                   'weight': 100}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'superaccept',
     'target_suit': 'D',
     'alertable': True},
    effects=[{'key': 'transfer_superaccept', 'target_suit': 'D', 'status': 'accepted'},
     {'key': 'agreed_suit', 'suit': 'D', 'source': 'minor_transfer_superaccept'}],
    description='Opener bids the gap 3C to superaccept the diamond transfer with honor-third or stronger support.',
    system_notes='After 1N-2N, 3C is the gap superaccept for diamonds.',
)

Call(
    id='cs_9',
    context={'auction_pattern': '1NP2NP', 'seat_positions': [1, 2, 3, 4]},
    bid='3D',
    requires={'state_exists': {'key': 'transfer', 'target_suit': 'D', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_diamond_transfer',
                   'evaluator': 'state_exists',
                   'query': {'key': 'transfer', 'target_suit': 'D', 'status': 'pending'},
                   'weight': 10}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'transfer_completion',
     'target_suit': 'D',
     'alertable': False},
    effects=[{'key': 'transfer_completion', 'target_suit': 'D', 'status': 'completed'}],
    description='Opener accepts the diamond transfer normally at 3D.',
    system_notes='After 1N-2N, 3D is the normal diamond transfer acceptance.',
)

Call(
    id='cs_10',
    context={'auction_pattern': '1NP2HP', 'seat_positions': [1, 2, 3, 4]},
    bid='2S',
    requires={'state_exists': {'key': 'transfer', 'target_suit': 'S', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_spade_transfer',
                   'evaluator': 'state_exists',
                   'query': {'key': 'transfer', 'target_suit': 'S', 'status': 'pending'},
                   'weight': 10}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'transfer_completion',
     'target_suit': 'S',
     'alertable': False},
    effects=[{'key': 'transfer_completion', 'target_suit': 'S', 'status': 'completed'}],
    description='Opener completes the spade transfer at 2S.',
    system_notes='After 1N-2H, 2S completes the spade transfer.',
)

Call(
    id='cs_11',
    context={'auction_pattern': '1NP2DP', 'seat_positions': [1, 2, 3, 4]},
    bid='3H',
    requires={'state_has': {'transfer': {'target_suit': 'H', 'status': 'pending'}}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_heart_transfer',
                   'evaluator': 'state_exists',
                   'query': {'key': 'transfer', 'target_suit': 'H', 'status': 'pending'},
                   'weight': 10},
                  {'criterion_id': 'four_heart_support',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 70},
                  {'criterion_id': 'maximum_notrump_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 16,
                   'weight': 80}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'superaccept',
     'target_suit': 'H',
     'alertable': True},
    effects=[{'key': 'transfer_superaccept', 'target_suit': 'H', 'status': 'accepted'},
     {'key': 'agreed_suit', 'suit': 'H', 'source': 'major_transfer_superaccept'}],
    description='Opener superaccepts the heart transfer at 3H with four-card support and maximum values.',
    system_notes='After 1N-2D, 3H is a heart-transfer superaccept with four-card heart support and maximum values.',
)

Call(
    id='cs_12',
    context={'auction_pattern': '1NP2HP', 'seat_positions': [1, 2, 3, 4]},
    bid='3S',
    requires={'state_has': {'transfer': {'target_suit': 'S', 'status': 'pending'}}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'pending_spade_transfer',
                   'evaluator': 'state_exists',
                   'query': {'key': 'transfer', 'target_suit': 'S', 'status': 'pending'},
                   'weight': 10},
                  {'criterion_id': 'four_spade_support',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 70},
                  {'criterion_id': 'maximum_notrump_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 16,
                   'weight': 80}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['directive', 'context_setting'],
     'action_type': 'superaccept',
     'target_suit': 'S',
     'alertable': True},
    effects=[{'key': 'transfer_superaccept', 'target_suit': 'S', 'status': 'accepted'},
     {'key': 'agreed_suit', 'suit': 'S', 'source': 'major_transfer_superaccept'}],
    description='Opener superaccepts the spade transfer at 3S with four-card support and maximum values.',
    system_notes='After 1N-2H, 3S is a spade-transfer superaccept with four-card spade support and maximum values.',
)
