# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '', 'seat_positions': [1, 2]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'opening_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 12,
                   'weight': 40},
                  {'criterion_id': 'five_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 5,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'context_initiating'],
     'action_type': 'opening',
     'target_suit': 'S',
     'shown_length_min': 5,
     'alertable': False},
    effects=[{'key': 'major_opening', 'actor_role': 'opener', 'target_suit': 'S', 'shown_length_min': 5}],
    description='Opens 1S naturally with opening values and at least five spades.',
    system_notes='1S opening is natural and shows at least five spades.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '', 'seat_positions': [1, 2]},
    bid='1H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'opening_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 12,
                   'weight': 40},
                  {'criterion_id': 'five_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 5,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'context_initiating'],
     'action_type': 'opening',
     'target_suit': 'H',
     'shown_length_min': 5,
     'alertable': False},
    effects=[{'key': 'major_opening', 'actor_role': 'opener', 'target_suit': 'H', 'shown_length_min': 5}],
    description='Opens 1H naturally with opening values and at least five hearts.',
    system_notes='1H opening is natural and shows at least five hearts.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '', 'seat_positions': [3, 4]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'third_or_fourth_seat_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 10,
                   'weight': 30},
                  {'criterion_id': 'five_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 5,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'context_initiating'],
     'action_type': 'opening',
     'target_suit': 'S',
     'shown_length_min': 5,
     'seat_style': 'third_or_fourth_seat_may_be_light',
     'alertable': False},
    effects=[{'key': 'major_opening',
      'actor_role': 'opener',
      'target_suit': 'S',
      'shown_length_min': 5,
      'seat_style': 'third_or_fourth_seat_may_be_light'}],
    description='Opens 1S in third or fourth seat with at least five spades; the profile policy decides whether a light opening is practical.',
    system_notes='Third- and fourth-seat 1S opening is natural, at least five spades, and may be lighter by partnership style.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '', 'seat_positions': [3, 4]},
    bid='1H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'third_or_fourth_seat_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 10,
                   'weight': 30},
                  {'criterion_id': 'five_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 5,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'context_initiating'],
     'action_type': 'opening',
     'target_suit': 'H',
     'shown_length_min': 5,
     'seat_style': 'third_or_fourth_seat_may_be_light',
     'alertable': False},
    effects=[{'key': 'major_opening',
      'actor_role': 'opener',
      'target_suit': 'H',
      'shown_length_min': 5,
      'seat_style': 'third_or_fourth_seat_may_be_light'}],
    description='Opens 1H in third or fourth seat with at least five hearts; the profile policy decides whether a light opening is practical.',
    system_notes='Third- and fourth-seat 1H opening is natural, at least five hearts, and may be lighter by partnership style.',
)

Call(
    id='cs_7',
    context={'auction_pattern': '', 'seat_positions': [3, 4]},
    bid='P',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'opening_pass_available',
                   'evaluator': 'expression',
                   'expr': {'const': True},
                   'weight': 1}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['final_placement'],
     'action_type': 'opening_pass',
     'alertable': False},
    description='Explicit pass candidate for third- and fourth-seat opening judgment.',
    system_notes='In third and fourth seat, pass is an explicit opening-route choice when the profile policy judges that opening is unattractive.',
)
