# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1NP', 'seat_positions': [1, 2, 3, 4]},
    bid='2C',
    requires={'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'invitational_or_better',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 8,
                   'weight': 30},
                  {'criterion_id': 'four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'or',
                            'args': [{'op': 'gte',
                                      'left': {'var': 'self.hearts.length'},
                                      'right': {'const': 4}},
                                     {'op': 'gte',
                                      'left': {'var': 'self.spades.length'},
                                      'right': {'const': 4}}]},
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry', 'context_initiating'],
     'action_type': 'stayman',
     'alertable': True},
    effects=[{'key': 'stayman', 'status': 'pending'}],
    description='Responder bids Stayman over 1N.',
    system_notes='After 1N, 2C is regular Stayman.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '1NP2CP', 'seat_positions': [1, 2, 3, 4]},
    bid='2D',
    requires={'state_exists': {'key': 'stayman', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lt',
                                      'left': {'var': 'self.hearts.length'},
                                      'right': {'const': 4}},
                                     {'op': 'lt',
                                      'left': {'var': 'self.spades.length'},
                                      'right': {'const': 4}}]},
                   'weight': 50}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['descriptive'],
     'action_type': 'stayman_response',
     'denies_four_card_major': True,
     'alertable': False},
    effects=[{'key': 'stayman_response', 'status': 'no_major'}],
    description='Opener denies a four-card major after regular Stayman.',
    system_notes='After regular Stayman, 2D denies a four-card major in this benchmark slice.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '1NP2CP2DP', 'seat_positions': [1, 2, 3, 4]},
    bid='2N',
    requires={'state_exists': {'key': 'stayman_response', 'status': 'no_major'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'invitational_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 8,
                   'max': 9,
                   'weight': 50}]},
    meaning={'nature_labels': ['natural', 'conventional'],
     'call_act_types': ['invitation'],
     'action_type': 'notrump_invitation',
     'alertable': True,
     'acbl_explanation': 'may or may not have a four-card major'},
    description='Responder rebids 2N as the invitational regular-Stayman route.',
    system_notes=("After Stayman and opener's response, 2N is invitational and may or may not include a four-card "
     'major.'),
)
