# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1SP', 'seat_positions': [3, 4]},
    bid='2C',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'exactly_three_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq', 'left': {'var': 'self.spades.length'}, 'right': {'const': 3}},
                   'weight': 50},
                  {'criterion_id': 'limit_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 10,
                   'max': 12,
                   'weight': 50}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive', 'inquiry'],
     'action_type': 'two_way_reverse_drury',
     'target_suit': 'S',
     'support_length': 3,
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'drury'},
     {'key': 'drury', 'suit': 'S', 'support_length': 3, 'status': 'pending'}],
    description='Two-way reverse Drury 2C by a passed hand, showing exactly three-card support.',
    system_notes=('By a passed hand after a seat 3 or 4 major opening, 2C is two-way reverse Drury with exactly '
     'three-card support.'),
)

Call(
    id='cs_2',
    context={'auction_pattern': '1SP', 'seat_positions': [3, 4]},
    bid='2D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'limit_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 10,
                   'max': 12,
                   'weight': 50}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive', 'inquiry'],
     'action_type': 'two_way_reverse_drury',
     'target_suit': 'S',
     'support_length_min': 4,
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'drury'},
     {'key': 'drury', 'suit': 'S', 'support_length_min': 4, 'status': 'pending'}],
    description='Two-way reverse Drury 2D by a passed hand, showing four-card or longer support.',
    system_notes=('By a passed hand after a seat 3 or 4 major opening, 2D is two-way reverse Drury with four-card '
     'or longer support.'),
)

Call(
    id='cs_3',
    context={'auction_pattern': '1HP', 'seat_positions': [3, 4]},
    bid='2C',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'exactly_three_hearts',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq', 'left': {'var': 'self.hearts.length'}, 'right': {'const': 3}},
                   'weight': 50},
                  {'criterion_id': 'limit_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 10,
                   'max': 12,
                   'weight': 50}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive', 'inquiry'],
     'action_type': 'two_way_reverse_drury',
     'target_suit': 'H',
     'support_length': 3,
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'drury'},
     {'key': 'drury', 'suit': 'H', 'support_length': 3, 'status': 'pending'}],
    description='Two-way reverse Drury 2C by a passed hand, showing exactly three-card heart support.',
    system_notes=('By a passed hand after a seat 3 or 4 major opening, 2C is two-way reverse Drury with exactly '
     'three-card heart support.'),
)

Call(
    id='cs_4',
    context={'auction_pattern': '1HP', 'seat_positions': [3, 4]},
    bid='2D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'limit_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 10,
                   'max': 12,
                   'weight': 50}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive', 'inquiry'],
     'action_type': 'two_way_reverse_drury',
     'target_suit': 'H',
     'support_length_min': 4,
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'drury'},
     {'key': 'drury', 'suit': 'H', 'support_length_min': 4, 'status': 'pending'}],
    description='Two-way reverse Drury 2D by a passed hand, showing four-card or longer heart support.',
    system_notes=('By a passed hand after a seat 3 or 4 major opening, 2D is two-way reverse Drury with four-card '
     'or longer heart support.'),
)
