# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='4D',
    requires={'all': [{'state_exists': {'key': 'agreed_suit', 'suit': 'D'}},
             {'not': {'state_exists': {'key': 'keycard_context', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'diamond_slam_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 12,
                   'weight': 80},
                  {'criterion_id': 'six_diamonds',
                   'evaluator': 'min_value',
                   'input': 'self.diamonds',
                   'min': 6,
                   'weight': 90}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry', 'keycard_asking', 'context_initiating'],
     'action_type': 'minorwood_1430',
     'target_suit': 'D',
     'alertable': True},
    capabilities=['start_frame', 'keycard_ask', 'slam_inquiry'],
    effects=[{'key': 'keycard_context',
      'trump_suit': 'D',
      'method': 'minorwood_1430',
      'status': 'pending'}],
    description='Asker bids 4D as Minorwood keycard for diamonds.',
    system_notes='With diamonds agreed, 4D asks for diamond keycards using 1430 steps.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '*'},
    bid='4H',
    requires={'all': [{'state_exists': {'key': 'keycard_context',
                              'method': 'minorwood_1430',
                              'trump_suit': 'D',
                              'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': 'minorwood_1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'one_or_four_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'in',
                            'left': {'op': 'keycard_count', 'hand': 'self', 'trump_suit': 'D'},
                            'right': {'const': [1, 4]}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_range': [1, 4],
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': 'D',
      'method': 'minorwood_1430',
      'response': 'one_or_four'}],
    description='Responder to diamond Minorwood answers 4H, showing 1 or 4 keycards.',
    system_notes='Over 4D Minorwood, 4H shows 1 or 4 keycards.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '*'},
    bid='4S',
    requires={'all': [{'state_exists': {'key': 'keycard_context',
                              'method': 'minorwood_1430',
                              'trump_suit': 'D',
                              'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': 'minorwood_1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'zero_or_three_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'in',
                            'left': {'op': 'keycard_count', 'hand': 'self', 'trump_suit': 'D'},
                            'right': {'const': [0, 3]}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_range': [0, 3],
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': 'D',
      'method': 'minorwood_1430',
      'response': 'zero_or_three'}],
    description='Responder to diamond Minorwood answers 4S, showing 0 or 3 keycards.',
    system_notes='Over 4D Minorwood, 4S shows 0 or 3 keycards.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '*'},
    bid='4N',
    requires={'all': [{'state_exists': {'key': 'keycard_context',
                              'method': 'minorwood_1430',
                              'trump_suit': 'D',
                              'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': 'minorwood_1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'two_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'keycard_count', 'hand': 'self', 'trump_suit': 'D'},
                            'right': {'const': 2}},
                   'weight': 100},
                  {'criterion_id': 'lacks_diamond_queen',
                   'evaluator': 'expression',
                   'expr': {'op': 'not',
                            'arg': {'op': 'contains_rank', 'hand': 'self', 'suit': 'D', 'rank': 'Q'}},
                   'weight': 20}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_count': 2,
     'trump_queen': False,
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': 'D',
      'method': 'minorwood_1430',
      'response': 'two_without_queen'}],
    description='Responder to diamond Minorwood answers 4N, showing two keycards without the diamond queen.',
    system_notes='Over 4D Minorwood, 4N shows 2 keycards without the diamond queen.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '*'},
    bid='5C',
    requires={'all': [{'state_exists': {'key': 'keycard_context',
                              'method': 'minorwood_1430',
                              'trump_suit': 'D',
                              'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': 'minorwood_1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'two_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'keycard_count', 'hand': 'self', 'trump_suit': 'D'},
                            'right': {'const': 2}},
                   'weight': 100},
                  {'criterion_id': 'has_diamond_queen',
                   'evaluator': 'expression',
                   'expr': {'op': 'contains_rank', 'hand': 'self', 'suit': 'D', 'rank': 'Q'},
                   'weight': 20}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_count': 2,
     'trump_queen': True,
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': 'D',
      'method': 'minorwood_1430',
      'response': 'two_with_queen'}],
    description='Responder to diamond Minorwood answers 5C, showing two keycards with the diamond queen.',
    system_notes='Over 4D Minorwood, 5C shows 2 keycards with the diamond queen.',
)
