# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='4C',
    requires={'all': [{'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
             {'not': {'state_exists': {'key': 'agreed_suit'}}},
             {'not': {'state_exists': {'key': 'transfer', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'stayman', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'ace_ask_context', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'notrump_slam_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 18,
                   'weight': 150},
                  {'criterion_id': 'balanced_or_semibalanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 30}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry', 'ace_asking', 'context_initiating'],
     'action_type': 'gerber_ace_ask',
     'target_suit': 'N',
     'alertable': True},
    capabilities=['start_frame', 'ace_ask', 'slam_inquiry'],
    effects=[{'key': 'ace_ask_context', 'method': 'gerber', 'target_suit': 'N', 'status': 'pending'}],
    description='Responder bids 4C as Gerber over a notrump-focused auction.',
    system_notes='After a notrump focus with no agreed suit, 4C asks for aces.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '*'},
    bid='4D',
    requires={'all': [{'state_exists': {'key': 'ace_ask_context', 'method': 'gerber', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'ace_ask_response', 'method': 'gerber'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'zero_or_four_aces',
                   'evaluator': 'expression',
                   'expr': {'op': 'in',
                            'left': {'op': 'ace_count', 'hand': 'self'},
                            'right': {'const': [0, 4]}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'ace_ask_response',
     'ace_range': [0, 4],
     'alertable': True},
    capabilities=['answer_frame', 'ace_response'],
    effects=[{'key': 'ace_ask_response', 'method': 'gerber', 'response': 'zero_or_four'}],
    description='Responder to Gerber answers 4D, showing zero or four aces.',
    system_notes='Over 4C Gerber, 4D shows 0 or 4 aces.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '*'},
    bid='4H',
    requires={'all': [{'state_exists': {'key': 'ace_ask_context', 'method': 'gerber', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'ace_ask_response', 'method': 'gerber'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'one_ace',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'ace_count', 'hand': 'self'},
                            'right': {'const': 1}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'ace_ask_response',
     'ace_count': 1,
     'alertable': True},
    capabilities=['answer_frame', 'ace_response'],
    effects=[{'key': 'ace_ask_response', 'method': 'gerber', 'response': 'one'}],
    description='Responder to Gerber answers 4H, showing one ace.',
    system_notes='Over 4C Gerber, 4H shows 1 ace.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '*'},
    bid='4S',
    requires={'all': [{'state_exists': {'key': 'ace_ask_context', 'method': 'gerber', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'ace_ask_response', 'method': 'gerber'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'two_aces',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'ace_count', 'hand': 'self'},
                            'right': {'const': 2}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'ace_ask_response',
     'ace_count': 2,
     'alertable': True},
    capabilities=['answer_frame', 'ace_response'],
    effects=[{'key': 'ace_ask_response', 'method': 'gerber', 'response': 'two'}],
    description='Responder to Gerber answers 4S, showing two aces.',
    system_notes='Over 4C Gerber, 4S shows 2 aces.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '*'},
    bid='4N',
    requires={'all': [{'state_exists': {'key': 'ace_ask_context', 'method': 'gerber', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'ace_ask_response', 'method': 'gerber'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'three_aces',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'ace_count', 'hand': 'self'},
                            'right': {'const': 3}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'ace_ask_response',
     'ace_count': 3,
     'alertable': True},
    capabilities=['answer_frame', 'ace_response'],
    effects=[{'key': 'ace_ask_response', 'method': 'gerber', 'response': 'three'}],
    description='Responder to Gerber answers 4N, showing three aces.',
    system_notes='Over 4C Gerber, 4N shows 3 aces.',
)
