# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='2C',
    requires={'all': [{'any': [{'state_exists': {'key': 'opener_notrump_rebid'}},
                      {'state_exists': {'key': 'opener_rebid'}}]},
             {'not': {'state_exists': {'key': 'checkback_relay'}}},
             {'not': {'state_exists': {'key': 'checkback_game_force'}}},
             {'not': {'state_exists': {'key': 'checkback_club_drop_dead'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'invitational_or_weak_diamonds',
                   'evaluator': 'expression',
                   'expr': {'op': 'or',
                            'args': [{'op': 'and',
                                      'args': [{'op': 'gte',
                                                'left': {'var': 'self.hcp'},
                                                'right': {'const': 11}},
                                               {'op': 'lte',
                                                'left': {'var': 'self.hcp'},
                                                'right': {'const': 12}}]},
                                     {'op': 'and',
                                      'args': [{'op': 'lte',
                                                'left': {'var': 'self.hcp'},
                                                'right': {'const': 7}},
                                               {'op': 'gte',
                                                'left': {'op': 'length', 'hand': 'self', 'suit': 'D'},
                                                'right': {'const': 5}}]}]},
                   'weight': 110}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay', 'context_initiating'],
     'action_type': 'checkback_two_club_relay',
     'relay_call': '2D',
     'alertable': True},
    effects=[{'key': 'checkback_relay',
      'relay_call': '2D',
      'status': 'pending',
      'strength_band': 'invitational_or_weak_diamonds'}],
    description='Responder starts the 2C relay in two-way New Minor Forcing or XYZ.',
    system_notes=('After 1X-1Y-1N or a three-call one-level auction, 2C relays to 2D for invitational hands or weak '
     'diamond signoff routes.'),
)

Call(
    id='cs_2',
    context={'auction_pattern': '*'},
    bid='2D',
    requires={'all': [{'any': [{'state_exists': {'key': 'opener_notrump_rebid'}},
                      {'state_exists': {'key': 'opener_rebid'}}]},
             {'not': {'state_exists': {'key': 'checkback_relay'}}},
             {'not': {'state_exists': {'key': 'checkback_game_force'}}},
             {'not': {'state_exists': {'key': 'checkback_club_drop_dead'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'game_force_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 13,
                   'weight': 120},
                  {'criterion_id': 'force_before_long_suit_rebid',
                   'evaluator': 'expression',
                   'required': False,
                   'expr': {'op': 'and',
                            'args': [{'op': 'gte', 'left': {'var': 'self.hcp'}, 'right': {'const': 13}},
                                     {'op': 'gte',
                                      'left': {'op': 'length',
                                               'hand': 'self',
                                               'suit': {'op': 'state_attribute',
                                                        'query': {'key': 'one_level_response'},
                                                        'attribute': 'target_suit'}},
                                      'right': {'const': 6}},
                                     {'op': 'state_missing',
                                      'query': {'key': 'partnership.force_status',
                                                'value': 'game_forcing'}}]},
                   'weight': 35},
                  {'criterion_id': 'major_or_shape_problem',
                   'evaluator': 'expression',
                   'expr': {'op': 'or',
                            'args': [{'op': 'gte',
                                      'left': {'op': 'length',
                                               'hand': 'self',
                                               'suit': {'op': 'state_attribute',
                                                        'query': {'key': 'one_level_response'},
                                                        'attribute': 'target_suit'}},
                                      'right': {'const': 5}},
                                     {'op': 'gte',
                                      'left': {'op': 'max',
                                               'args': [{'op': 'length', 'hand': 'self', 'suit': 'H'},
                                                        {'op': 'length', 'hand': 'self', 'suit': 'S'}]},
                                      'right': {'const': 4}}]},
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry', 'game_forcing', 'context_initiating'],
     'action_type': 'checkback_game_force',
     'alertable': True},
    effects=[{'key': 'checkback_game_force', 'status': 'pending'},
     {'state': {'key': 'partnership.force_status',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'game_forcing',
                'source': 'checkback_game_force'}},
     {'state': {'key': 'responder.route_purpose',
                'namespace': 'private',
                'owner': 'responder',
                'value': 'establish_force_before_describing_long_suit_or_shape',
                'source': 'checkback_game_force'}}],
    description='Responder starts the 2D game-forcing checkback route in two-way NMF or XYZ.',
    system_notes='After 1X-1Y-1N or a three-call one-level auction, 2D is artificial and game forcing.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '*'},
    bid='2N',
    requires={'all': [{'any': [{'state_exists': {'key': 'opener_notrump_rebid'}},
                      {'state_exists': {'key': 'opener_rebid'}}]},
             {'not': {'state_exists': {'key': 'checkback_relay'}}},
             {'not': {'state_exists': {'key': 'checkback_game_force'}}},
             {'not': {'state_exists': {'key': 'checkback_club_drop_dead'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_club_drop_dead',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte', 'left': {'var': 'self.hcp'}, 'right': {'const': 7}},
                                     {'op': 'gte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'C'},
                                      'right': {'const': 5}}]},
                   'weight': 120}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay', 'signoff_preparation', 'context_initiating'],
     'action_type': 'checkback_two_notrump_club_relay',
     'relay_call': '3C',
     'alertable': True},
    effects=[{'key': 'checkback_club_drop_dead', 'relay_call': '3C', 'status': 'pending'}],
    description='Responder bids 2N as a transfer to 3C for weak club drop-dead routes.',
    system_notes='In the benchmark XYZ structure, 2N transfers opener to 3C, usually to play there.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '*'},
    bid='3C',
    requires={'all': [{'any': [{'state_exists': {'key': 'opener_notrump_rebid'}},
                      {'state_exists': {'key': 'opener_rebid'}}]},
             {'not': {'state_exists': {'key': 'checkback_relay'}}},
             {'not': {'state_exists': {'key': 'checkback_game_force'}}},
             {'not': {'state_exists': {'key': 'checkback_club_drop_dead'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'slam_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 16,
                   'weight': 100},
                  {'criterion_id': 'five_clubs',
                   'evaluator': 'min_value',
                   'input': 'self.clubs',
                   'min': 5,
                   'weight': 60}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['slam_try', 'descriptive'],
     'action_type': 'natural_slam_try',
     'target_suit': 'C',
     'alertable': False},
    effects=[{'key': 'slam_interest',
      'target_suit': 'C',
      'status': 'active',
      'source': 'checkback_structure'}],
    description='Responder makes a natural club slam try instead of using the 2N drop-dead relay.',
    system_notes='In the benchmark checkback/XYZ structure, 3C is a natural slam try.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '*'},
    bid='3D',
    requires={'all': [{'any': [{'state_exists': {'key': 'opener_notrump_rebid'}},
                      {'state_exists': {'key': 'opener_rebid'}}]},
             {'not': {'state_exists': {'key': 'checkback_relay'}}},
             {'not': {'state_exists': {'key': 'checkback_game_force'}}},
             {'not': {'state_exists': {'key': 'checkback_club_drop_dead'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'slam_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 16,
                   'weight': 100},
                  {'criterion_id': 'five_diamonds',
                   'evaluator': 'min_value',
                   'input': 'self.diamonds',
                   'min': 5,
                   'weight': 60}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['slam_try', 'descriptive'],
     'action_type': 'natural_slam_try',
     'target_suit': 'D',
     'alertable': False},
    effects=[{'key': 'slam_interest',
      'target_suit': 'D',
      'status': 'active',
      'source': 'checkback_structure'}],
    description='Responder makes a natural diamond slam try.',
    system_notes='In the benchmark checkback/XYZ structure, 3D is a natural slam try.',
)

Call(
    id='cs_6',
    context={'auction_pattern': '*'},
    bid='2D',
    requires={'all': [{'state_exists': {'key': 'checkback_relay', 'relay_call': '2D', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'checkback_relay_completion',
                                      'relay_call': '2D',
                                      'status': 'completed'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'relay_pending',
                   'evaluator': 'state_exists',
                   'query': {'key': 'checkback_relay', 'relay_call': '2D', 'status': 'pending'},
                   'weight': 120}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_completion'],
     'action_type': 'checkback_relay_completion',
     'alertable': True},
    effects=[{'key': 'checkback_relay_completion', 'relay_call': '2D', 'status': 'completed'}],
    description='Opener completes the 2C checkback relay by bidding 2D.',
    system_notes='Over the artificial 2C checkback relay, opener bids 2D as requested.',
)

Call(
    id='cs_7',
    context={'auction_pattern': '*'},
    bid='P',
    requires={'state_exists': {'key': 'checkback_relay_completion',
                     'relay_call': '2D',
                     'status': 'completed'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_diamond_drop_dead',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte', 'left': {'var': 'self.hcp'}, 'right': {'const': 7}},
                                     {'op': 'gte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'D'},
                                      'right': {'const': 5}}]},
                   'weight': 120}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['signoff', 'final_placement'],
     'action_type': 'pass_final_contract',
     'target_suit': 'D',
     'level': 2,
     'alertable': False},
    effects=[{'key': 'final_contract', 'target_suit': 'D', 'level': 2, 'source': 'checkback_structure'}],
    description='Responder passes 2D after the checkback relay with weak diamonds.',
    system_notes='After 2C-2D in the checkback structure, pass is the weak diamond signoff route.',
)

Call(
    id='cs_8',
    context={'auction_pattern': '*'},
    bid='2N',
    requires={'state_exists': {'key': 'checkback_relay_completion',
                     'relay_call': '2D',
                     'status': 'completed'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'invitational_notrump',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 11,
                   'max': 12,
                   'weight': 120},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['invitational'],
     'action_type': 'notrump_invite',
     'target_suit': 'N',
     'level': 2,
     'alertable': False},
    effects=[{'key': 'game_invite', 'target_suit': 'N', 'source': 'checkback_structure'}],
    description='Responder rebids 2N after the 2C-2D relay with invitational notrump values.',
    system_notes='After 2C-2D in the checkback structure, 2N is invitational.',
)

Call(
    id='cs_9',
    context={'auction_pattern': '*'},
    bid='3C',
    requires={'all': [{'state_exists': {'key': 'checkback_club_drop_dead',
                              'relay_call': '3C',
                              'status': 'pending'}},
             {'not': {'state_exists': {'key': 'checkback_club_drop_dead_completion',
                                      'target_suit': 'C',
                                      'status': 'completed'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'club_relay_pending',
                   'evaluator': 'state_exists',
                   'query': {'key': 'checkback_club_drop_dead',
                             'relay_call': '3C',
                             'status': 'pending'},
                   'weight': 120}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_completion'],
     'action_type': 'checkback_club_relay_completion',
     'alertable': True},
    effects=[{'key': 'checkback_club_drop_dead_completion', 'target_suit': 'C', 'status': 'completed'}],
    description='Opener completes the 2N club relay by bidding 3C.',
    system_notes='Over the artificial 2N club relay, opener bids 3C as requested.',
)

Call(
    id='cs_10',
    context={'auction_pattern': '*'},
    bid='P',
    requires={'state_exists': {'key': 'checkback_club_drop_dead_completion',
                     'target_suit': 'C',
                     'status': 'completed'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_club_drop_dead',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte', 'left': {'var': 'self.hcp'}, 'right': {'const': 7}},
                                     {'op': 'gte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'C'},
                                      'right': {'const': 5}}]},
                   'weight': 120}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['signoff', 'final_placement'],
     'action_type': 'pass_final_contract',
     'target_suit': 'C',
     'level': 3,
     'alertable': False},
    effects=[{'key': 'final_contract', 'target_suit': 'C', 'level': 3, 'source': 'checkback_structure'}],
    description='Responder passes 3C after the 2N-3C relay with weak clubs.',
    system_notes='After 2N-3C in the checkback structure, pass is the weak club signoff route.',
)

Call(
    id='cs_11',
    context={'auction_pattern': '*'},
    bid='2H',
    requires={'state_exists': {'key': 'checkback_game_force', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'responder_bid_hearts',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'state_attribute',
                                     'query': {'key': 'one_level_response'},
                                     'attribute': 'target_suit'},
                            'right': {'const': 'H'}},
                   'weight': 40},
                  {'criterion_id': 'three_heart_support',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 3,
                   'weight': 90}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['support_showing'],
     'action_type': 'checkback_support_showing',
     'target_suit': 'H',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'checkback_game_force'}],
    description='Opener shows three-card heart support over the 2D game-forcing checkback ask.',
    system_notes=('Over artificial 2D checkback, opener bids 2H with three-card heart support when hearts were '
     "responder's suit."),
)

Call(
    id='cs_12',
    context={'auction_pattern': '*'},
    bid='2S',
    requires={'state_exists': {'key': 'checkback_game_force', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'responder_bid_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'state_attribute',
                                     'query': {'key': 'one_level_response'},
                                     'attribute': 'target_suit'},
                            'right': {'const': 'S'}},
                   'weight': 40},
                  {'criterion_id': 'three_spade_support',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 3,
                   'weight': 90}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['support_showing'],
     'action_type': 'checkback_support_showing',
     'target_suit': 'S',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'checkback_game_force'}],
    description='Opener shows three-card spade support over the 2D game-forcing checkback ask.',
    system_notes=('Over artificial 2D checkback, opener bids 2S with three-card spade support when spades were '
     "responder's suit."),
)

Call(
    id='cs_13',
    context={'auction_pattern': '*'},
    bid='2N',
    requires={'state_exists': {'key': 'checkback_game_force', 'status': 'pending'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'no_three_card_support',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length',
                                     'hand': 'self',
                                     'suit': {'op': 'state_attribute',
                                              'query': {'key': 'one_level_response'},
                                              'attribute': 'target_suit'}},
                            'right': {'const': 2}},
                   'weight': 100}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'checkback_no_support',
     'target_suit': 'N',
     'level': 2,
     'alertable': False},
    description='Opener rebids 2N over the 2D game-forcing checkback ask without three-card support.',
    system_notes=("Over artificial 2D checkback, 2N denies three-card support for responder's major in this "
     'benchmark slice.'),
)
