# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='4D',
    requires={'all': [{'state_exists': {'key': 'agreed_suit', 'suit': 'H'}},
             {'state_exists': {'key': 'transfer_superaccept',
                              'target_suit': 'H',
                              'status': 'accepted'}},
             {'not': {'state_exists': {'key': 'keycard_context', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'heart_slam_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 16,
                   'weight': 90},
                  {'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 60},
                  {'criterion_id': 'diamond_control',
                   'evaluator': 'expression',
                   'expr': {'op': 'or',
                            'args': [{'op': 'contains_rank', 'hand': 'self', 'suit': 'D', 'rank': 'A'},
                                     {'op': 'contains_rank', 'hand': 'self', 'suit': 'D', 'rank': 'K'},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'D'},
                                      'right': {'const': 1}}]},
                   'weight': 110}]},
    meaning={'nature_labels': ['conventional'],
     'call_act_types': ['control_showing', 'slam_try', 'context_setting'],
     'action_type': 'control_bid',
     'target_suit': 'D',
     'agreed_suit': 'H',
     'control_round': 'first_or_second',
     'alertable': False},
    effects=[{'key': 'control',
      'suit': 'D',
      'agreed_suit': 'H',
      'round': 'first_or_second',
      'status': 'shown'},
     {'key': 'slam_interest', 'agreed_suit': 'H', 'status': 'active', 'source': 'control_bid'}],
    description=('Responder bids 4D after a heart-transfer superaccept to show diamond control and continue slam '
     'exploration.'),
    system_notes='After 1N-2D-3H, 4D shows diamond control and heart-slam interest.',
)
