# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1SP', 'seat_positions': [1, 2]},
    bid='2S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'exactly_three_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq', 'left': {'var': 'self.spades.length'}, 'right': {'const': 3}},
                   'weight': 50},
                  {'criterion_id': 'simple_raise_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 6,
                   'max': 10,
                   'weight': 50}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'simple_raise',
     'target_suit': 'S',
     'support_length': 3,
     'raise_strength': 'simple',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'simple_raise'},
     {'key': 'major_raise', 'suit': 'S', 'raise_type': 'simple'}],
    description='Responder gives a simple spade raise with exactly three-card support and non-forcing values.',
    system_notes=('After 1S, 2S is a natural simple raise. In this benchmark, Bergen handles four-card constructive '
     'and limit raises.'),
)

Call(
    id='cs_2',
    context={'auction_pattern': '1HP', 'seat_positions': [1, 2]},
    bid='2H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'exactly_three_hearts',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq', 'left': {'var': 'self.hearts.length'}, 'right': {'const': 3}},
                   'weight': 50},
                  {'criterion_id': 'simple_raise_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 6,
                   'max': 10,
                   'weight': 50}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'simple_raise',
     'target_suit': 'H',
     'support_length': 3,
     'raise_strength': 'simple',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'simple_raise'},
     {'key': 'major_raise', 'suit': 'H', 'raise_type': 'simple'}],
    description='Responder gives a simple heart raise with exactly three-card support and non-forcing values.',
    system_notes=('After 1H, 2H is a natural simple raise. In this benchmark, Bergen handles four-card constructive '
     'and limit raises.'),
)
