# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='4N',
    requires={'all': [{'state_exists': {'key': 'notrump_focus', 'status': 'active'}},
             {'not': {'state_exists': {'key': 'agreed_suit'}}},
             {'not': {'state_exists': {'key': 'transfer', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'texas_transfer', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'texas_transfer', 'status': 'completed'}}},
             {'not': {'state_exists': {'key': 'stayman', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'puppet_stayman', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'quantitative_slam_invite_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 16,
                   'max': 17,
                   'weight': 120},
                  {'criterion_id': 'balanced_shape',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 40}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['invitation'],
     'action_type': 'quantitative_notrump_invite',
     'target_suit': 'N',
     'level': 4,
     'alertable': False},
    effects=[{'key': 'quantitative_notrump_invite', 'target_suit': 'N', 'level': 4, 'status': 'pending'}],
    description='Responder bids 4N as a quantitative notrump slam invitation.',
    system_notes='With notrump focus and no agreed suit, 4N is quantitative.',
)
