# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '', 'seat_positions': [1, 2, 3, 4]},
    bid='1D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'opening_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 12,
                   'weight': 40},
                  {'criterion_id': 'four_diamonds',
                   'evaluator': 'min_value',
                   'input': 'self.diamonds',
                   'min': 4,
                   'weight': 60},
                  {'criterion_id': 'no_five_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 4}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 4}}]},
                   'weight': 30},
                  {'criterion_id': 'diamonds_at_least_clubs',
                   'evaluator': 'expression',
                   'expr': {'op': 'gte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'D'},
                            'right': {'op': 'length', 'hand': 'self', 'suit': 'C'}},
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'context_initiating'],
     'action_type': 'opening',
     'target_suit': 'D',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'minor_opening', 'actor_role': 'opener', 'target_suit': 'D', 'shown_length_min': 4},
     {'state': {'key': 'opener.length.D',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 4,
                'source': 'minor_opening'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 4,
                'source': 'minor_opening_denial'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 4,
                'source': 'minor_opening_denial'}}],
    description=('Opens 1D naturally with opening values, at least four diamonds, no five-card major, and diamonds '
     'at least as long as clubs.'),
    system_notes='1D opening is natural, usually four or more diamonds, and denies a five-card major.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '', 'seat_positions': [1, 2, 3, 4]},
    bid='1C',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'opening_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 12,
                   'weight': 40},
                  {'criterion_id': 'three_clubs',
                   'evaluator': 'min_value',
                   'input': 'self.clubs',
                   'min': 3,
                   'weight': 50},
                  {'criterion_id': 'no_five_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 4}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 4}}]},
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'context_initiating'],
     'action_type': 'opening',
     'target_suit': 'C',
     'shown_length_min': 3,
     'alertable': False},
    effects=[{'key': 'minor_opening', 'actor_role': 'opener', 'target_suit': 'C', 'shown_length_min': 3},
     {'state': {'key': 'opener.length.C',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 3,
                'source': 'minor_opening'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 4,
                'source': 'minor_opening_denial'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 4,
                'source': 'minor_opening_denial'}}],
    description='Opens 1C naturally with opening values, at least three clubs, and no five-card major.',
    system_notes='1C opening is natural, may be three cards, and denies a five-card major.',
)
