# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_18',
    context={'auction_pattern': '1CP1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='1H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'opener_rebid',
     'target_suit': 'H',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'opener_rebid', 'target_suit': 'H', 'shown_length_min': 4},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 4,
                'source': 'opener_rebid'}}],
    description='Opener rebids 1H after 1C-1D with a four-card heart suit.',
    system_notes='After 1C-1D, 1H is natural and shows hearts.',
)

Call(
    id='cs_19',
    context={'auction_pattern': '1CP1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 70},
                  {'criterion_id': 'hearts_not_first',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                            'right': {'const': 3}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'opener_rebid',
     'target_suit': 'S',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'opener_rebid', 'target_suit': 'S', 'shown_length_min': 4},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 4,
                'source': 'opener_rebid'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'one_level_spade_rebid_denial'}}],
    description='Opener rebids 1S after 1C-1D with four spades and fewer than four hearts.',
    system_notes='After 1C-1D, 1S is natural and shows spades.',
)

Call(
    id='cs_20',
    context={'auction_pattern': '1CP1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'twelve_to_fourteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 70},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_rebid',
     'hcp_range': [12, 14],
     'alertable': False},
    effects=[{'key': 'opener_notrump_rebid', 'hcp_min': 12, 'hcp_max': 14},
     {'state': {'key': 'opener.hcp',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 12,
                'max_value': 14,
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.shape',
                'namespace': 'public',
                'owner': 'opener',
                'value': 'balanced',
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}}],
    description='Opener rebids 1N after 1C-1D with 12-14 balanced values and no four-card major.',
    system_notes='After 1C-1D, 1N shows a minimum balanced hand.',
)

Call(
    id='cs_21',
    context={'auction_pattern': '1CP1HP', 'seat_positions': [1, 2, 3, 4]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'opener_rebid',
     'target_suit': 'S',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'opener_rebid', 'target_suit': 'S', 'shown_length_min': 4},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 4,
                'source': 'opener_rebid'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'one_level_spade_rebid_denial'}}],
    description='Opener rebids 1S after 1C-1H with four spades.',
    system_notes='After 1C-1H, 1S is natural and shows spades.',
)

Call(
    id='cs_22',
    context={'auction_pattern': '1CP1HP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'twelve_to_fourteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 70},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'fewer_than_four_hearts',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                            'right': {'const': 3}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_rebid',
     'hcp_range': [12, 14],
     'alertable': False},
    effects=[{'key': 'opener_notrump_rebid', 'hcp_min': 12, 'hcp_max': 14},
     {'state': {'key': 'opener.hcp',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 12,
                'max_value': 14,
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.shape',
                'namespace': 'public',
                'owner': 'opener',
                'value': 'balanced',
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}}],
    description='Opener rebids 1N after 1C-1H with 12-14 balanced values and no heart support.',
    system_notes='After 1C-1H, 1N shows a minimum balanced hand.',
)

Call(
    id='cs_23',
    context={'auction_pattern': '1CP1HP', 'seat_positions': [1, 2, 3, 4]},
    bid='2H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'three_plus_heart_support',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 3,
                   'weight': 80},
                  {'criterion_id': 'minimum_opening',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['support_showing'],
     'action_type': 'raise',
     'target_suit': 'H',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'minor_opener_raise'},
     {'state': {'key': 'partnership.force_status',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'not_forcing',
                'source': 'simple_raise'}},
     {'state': {'key': 'partnership.agreed_suit',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'H',
                'source': 'minor_opener_raise'}}],
    description='Opener raises hearts after 1C-1H with three-card or longer support.',
    system_notes='After 1C-1H, 2H shows heart support and minimum opening values.',
)

Call(
    id='cs_24',
    context={'auction_pattern': '1CP1SP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'twelve_to_fourteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 70},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'fewer_than_four_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                            'right': {'const': 3}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_rebid',
     'hcp_range': [12, 14],
     'alertable': False},
    effects=[{'key': 'opener_notrump_rebid', 'hcp_min': 12, 'hcp_max': 14},
     {'state': {'key': 'opener.hcp',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 12,
                'max_value': 14,
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.shape',
                'namespace': 'public',
                'owner': 'opener',
                'value': 'balanced',
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}}],
    description='Opener rebids 1N after 1C-1S with 12-14 balanced values and no spade support.',
    system_notes='After 1C-1S, 1N shows a minimum balanced hand.',
)

Call(
    id='cs_25',
    context={'auction_pattern': '1CP1SP', 'seat_positions': [1, 2, 3, 4]},
    bid='2S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'three_plus_spade_support',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 3,
                   'weight': 80},
                  {'criterion_id': 'minimum_opening',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['support_showing'],
     'action_type': 'raise',
     'target_suit': 'S',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'minor_opener_raise'},
     {'state': {'key': 'partnership.force_status',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'not_forcing',
                'source': 'simple_raise'}},
     {'state': {'key': 'partnership.agreed_suit',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'S',
                'source': 'minor_opener_raise'}}],
    description='Opener raises spades after 1C-1S with three-card or longer support.',
    system_notes='After 1C-1S, 2S shows spade support and minimum opening values.',
)

Call(
    id='cs_26',
    context={'auction_pattern': '1DP1HP', 'seat_positions': [1, 2, 3, 4]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'opener_rebid',
     'target_suit': 'S',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'opener_rebid', 'target_suit': 'S', 'shown_length_min': 4},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 4,
                'source': 'opener_rebid'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'one_level_spade_rebid_denial'}}],
    description='Opener rebids 1S after 1D-1H with four spades.',
    system_notes='After 1D-1H, 1S is natural and shows spades.',
)

Call(
    id='cs_27',
    context={'auction_pattern': '1DP1HP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'twelve_to_fourteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 70},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'fewer_than_four_hearts',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                            'right': {'const': 3}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_rebid',
     'hcp_range': [12, 14],
     'alertable': False},
    effects=[{'key': 'opener_notrump_rebid', 'hcp_min': 12, 'hcp_max': 14},
     {'state': {'key': 'opener.hcp',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 12,
                'max_value': 14,
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.shape',
                'namespace': 'public',
                'owner': 'opener',
                'value': 'balanced',
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.length.H',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}}],
    description='Opener rebids 1N after 1D-1H with 12-14 balanced values and no heart support.',
    system_notes='After 1D-1H, 1N shows a minimum balanced hand.',
)

Call(
    id='cs_28',
    context={'auction_pattern': '1DP1HP', 'seat_positions': [1, 2, 3, 4]},
    bid='2H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'three_plus_heart_support',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 3,
                   'weight': 80},
                  {'criterion_id': 'minimum_opening',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['support_showing'],
     'action_type': 'raise',
     'target_suit': 'H',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'minor_opener_raise'},
     {'state': {'key': 'partnership.force_status',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'not_forcing',
                'source': 'simple_raise'}},
     {'state': {'key': 'partnership.agreed_suit',
                'namespace': 'public',
                'owner': 'partnership',
                'value': 'H',
                'source': 'minor_opener_raise'}}],
    description='Opener raises hearts after 1D-1H with three-card or longer support.',
    system_notes='After 1D-1H, 2H shows heart support and minimum opening values.',
)

Call(
    id='cs_29',
    context={'auction_pattern': '1DP1SP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'twelve_to_fourteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 70},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'fewer_than_four_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                            'right': {'const': 3}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_rebid',
     'hcp_range': [12, 14],
     'alertable': False},
    effects=[{'key': 'opener_notrump_rebid', 'hcp_min': 12, 'hcp_max': 14},
     {'state': {'key': 'opener.hcp',
                'namespace': 'public',
                'owner': 'opener',
                'min_value': 12,
                'max_value': 14,
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.shape',
                'namespace': 'public',
                'owner': 'opener',
                'value': 'balanced',
                'source': 'notrump_rebid'}},
     {'state': {'key': 'opener.length.S',
                'namespace': 'public',
                'owner': 'opener',
                'max_value': 3,
                'source': 'notrump_rebid_denial'}}],
    description='Opener rebids 1N after 1D-1S with 12-14 balanced values and no spade support.',
    system_notes='After 1D-1S, 1N shows a minimum balanced hand.',
)

Call(
    id='cs_30',
    context={'auction_pattern': '1DP1SP', 'seat_positions': [1, 2, 3, 4]},
    bid='2S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'three_plus_spade_support',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 3,
                   'weight': 80},
                  {'criterion_id': 'minimum_opening',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 12,
                   'max': 14,
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['support_showing'],
     'action_type': 'raise',
     'target_suit': 'S',
     'alertable': False},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'minor_opener_raise'}],
    description='Opener raises spades after 1D-1S with three-card or longer support.',
    system_notes='After 1D-1S, 2S shows spade support and minimum opening values.',
)

