# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_3',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='1D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'constructive_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 6,
                   'weight': 30},
                  {'criterion_id': 'four_diamonds',
                   'evaluator': 'min_value',
                   'input': 'self.diamonds',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'one_level_response',
     'target_suit': 'D',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'one_level_response', 'target_suit': 'D', 'shown_length_min': 4},
     {'state': {'key': 'responder.length.D',
                'namespace': 'public',
                'owner': 'responder',
                'min_value': 4,
                'source': 'one_level_response'}}],
    description='Responds 1D to 1C with four or more diamonds, constructive values, and no four-card major.',
    system_notes='After 1C, 1D is natural. One-level major responses may bypass diamonds.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='1H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'constructive_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 6,
                   'weight': 30},
                  {'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 60},
                  {'criterion_id': 'not_five_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                            'right': {'const': 4}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'one_level_response',
     'target_suit': 'H',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'one_level_response', 'target_suit': 'H', 'shown_length_min': 4},
     {'state': {'key': 'responder.length.H',
                'namespace': 'public',
                'owner': 'responder',
                'min_value': 4,
                'source': 'one_level_response'}}],
    description='Responds 1H to a minor opening with at least four hearts; with 4-4 majors, hearts are bid first.',
    system_notes='After one of a minor, 1H shows hearts and may bypass diamonds after 1C.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'constructive_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 6,
                   'weight': 30},
                  {'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 60},
                  {'criterion_id': 'spade_priority_shape',
                   'evaluator': 'expression',
                   'expr': {'op': 'or',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'gte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 5}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'one_level_response',
     'target_suit': 'S',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'one_level_response', 'target_suit': 'S', 'shown_length_min': 4},
     {'state': {'key': 'responder.length.S',
                'namespace': 'public',
                'owner': 'responder',
                'min_value': 4,
                'source': 'one_level_response'}}],
    description='Responds 1S to 1C with at least four spades; with 5S4H, spades are bid first.',
    system_notes='After 1C, 1S shows spades and may bypass diamonds.',
)

Call(
    id='cs_6',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='1H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'constructive_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 6,
                   'weight': 30},
                  {'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 60},
                  {'criterion_id': 'not_five_spades',
                   'evaluator': 'expression',
                   'expr': {'op': 'lte',
                            'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                            'right': {'const': 4}},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'one_level_response',
     'target_suit': 'H',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'one_level_response', 'target_suit': 'H', 'shown_length_min': 4},
     {'state': {'key': 'responder.length.H',
                'namespace': 'public',
                'owner': 'responder',
                'min_value': 4,
                'source': 'one_level_response'}}],
    description='Responds 1H to 1D with at least four hearts; with 4-4 majors, hearts are bid first.',
    system_notes='After 1D, 1H shows hearts.',
)

Call(
    id='cs_7',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='1S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'constructive_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 6,
                   'weight': 30},
                  {'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 60},
                  {'criterion_id': 'spade_priority_shape',
                   'evaluator': 'expression',
                   'expr': {'op': 'or',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'gte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 5}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'one_level_response',
     'target_suit': 'S',
     'shown_length_min': 4,
     'alertable': False},
    effects=[{'key': 'one_level_response', 'target_suit': 'S', 'shown_length_min': 4},
     {'state': {'key': 'responder.length.S',
                'namespace': 'public',
                'owner': 'responder',
                'min_value': 4,
                'source': 'one_level_response'}}],
    description='Responds 1S to a 1D opening with at least four spades.',
    system_notes='After 1D, 1S shows spades.',
)

Call(
    id='cs_8',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'six_to_ten',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 6,
                   'max': 10,
                   'weight': 50},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_response',
     'hcp_range': [6, 10],
     'alertable': False},
    effects=[{'key': 'notrump_response', 'hcp_min': 6, 'hcp_max': 10}],
    description='Responds 1N to 1C with 6-10 balanced-ish values and no four-card major.',
    system_notes='After 1C, 1N shows about 6-10 HCP and denies a four-card major.',
)

Call(
    id='cs_9',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='1N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'six_to_ten',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 6,
                   'max': 10,
                   'weight': 50},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 30}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive'],
     'action_type': 'notrump_response',
     'hcp_range': [6, 10],
     'alertable': False},
    effects=[{'key': 'notrump_response', 'hcp_min': 6, 'hcp_max': 10}],
    description='Responds 1N to 1D with 6-10 balanced-ish values and no four-card major.',
    system_notes='After 1D, 1N shows about 6-10 HCP and denies a four-card major.',
)

Call(
    id='cs_10',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='2N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'eleven_to_twelve',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 11,
                   'max': 12,
                   'weight': 80},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'invitational'],
     'action_type': 'notrump_response',
     'hcp_range': [11, 12],
     'alertable': False},
    effects=[{'key': 'notrump_response', 'hcp_min': 11, 'hcp_max': 12}],
    description='Responds 2N to a minor opening with 11-12 balanced values and no four-card major.',
    system_notes='After one of a minor, 2N shows about 11-12 HCP balanced.',
)

Call(
    id='cs_11',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='2N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'eleven_to_twelve',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 11,
                   'max': 12,
                   'weight': 80},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'invitational'],
     'action_type': 'notrump_response',
     'hcp_range': [11, 12],
     'alertable': False},
    effects=[{'key': 'notrump_response', 'hcp_min': 11, 'hcp_max': 12}],
    description='Responds 2N to 1D with 11-12 balanced values and no four-card major.',
    system_notes='After 1D, 2N shows about 11-12 HCP balanced.',
)

Call(
    id='cs_12',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='3N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'thirteen_to_fifteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 13,
                   'max': 15,
                   'weight': 90},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'N',
     'level': 3,
     'hcp_range': [13, 15],
     'alertable': False},
    effects=[{'key': 'final_contract',
      'target_suit': 'N',
      'level': 3,
      'source': 'minor_notrump_response'}],
    description='Responds 3N to a minor opening with 13-15 balanced values and no four-card major.',
    system_notes='After one of a minor, 3N shows about 13-15 HCP balanced.',
)

Call(
    id='cs_13',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='3N',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'thirteen_to_fifteen',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 13,
                   'max': 15,
                   'weight': 90},
                  {'criterion_id': 'balanced',
                   'evaluator': 'equals',
                   'input': 'self.balanced',
                   'value': True,
                   'weight': 20},
                  {'criterion_id': 'no_four_card_major',
                   'evaluator': 'expression',
                   'expr': {'op': 'and',
                            'args': [{'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'H'},
                                      'right': {'const': 3}},
                                     {'op': 'lte',
                                      'left': {'op': 'length', 'hand': 'self', 'suit': 'S'},
                                      'right': {'const': 3}}]},
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['descriptive', 'final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'N',
     'level': 3,
     'hcp_range': [13, 15],
     'alertable': False},
    effects=[{'key': 'final_contract',
      'target_suit': 'N',
      'level': 3,
      'source': 'minor_notrump_response'}],
    description='Responds 3N to 1D with 13-15 balanced values and no four-card major.',
    system_notes='After 1D, 3N shows about 13-15 HCP balanced.',
)

Call(
    id='cs_14',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='2H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_range',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 3,
                   'max': 7,
                   'weight': 60},
                  {'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural', 'weak'],
     'call_act_types': ['descriptive', 'preemptive'],
     'action_type': 'weak_jump_shift',
     'target_suit': 'H',
     'shown_length_min': 6,
     'alertable': True},
    effects=[{'key': 'weak_jump_shift', 'target_suit': 'H', 'shown_length_min': 6}],
    description='Weak jump-shift response 2H to 1C.',
    system_notes='After 1C, 2H is weak and natural, not Soloway.',
)

Call(
    id='cs_15',
    context={'auction_pattern': '1CP', 'seat_positions': [1, 2, 3, 4]},
    bid='2S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_range',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 3,
                   'max': 7,
                   'weight': 60},
                  {'criterion_id': 'six_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 6,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural', 'weak'],
     'call_act_types': ['descriptive', 'preemptive'],
     'action_type': 'weak_jump_shift',
     'target_suit': 'S',
     'shown_length_min': 6,
     'alertable': True},
    effects=[{'key': 'weak_jump_shift', 'target_suit': 'S', 'shown_length_min': 6}],
    description='Weak jump-shift response 2S to 1C.',
    system_notes='After 1C, 2S is weak and natural, not Soloway.',
)

Call(
    id='cs_16',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='2H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_range',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 3,
                   'max': 7,
                   'weight': 60},
                  {'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural', 'weak'],
     'call_act_types': ['descriptive', 'preemptive'],
     'action_type': 'weak_jump_shift',
     'target_suit': 'H',
     'shown_length_min': 6,
     'alertable': True},
    effects=[{'key': 'weak_jump_shift', 'target_suit': 'H', 'shown_length_min': 6}],
    description='Weak jump-shift response 2H to 1D.',
    system_notes='After 1D, 2H is weak and natural, not Soloway.',
)

Call(
    id='cs_17',
    context={'auction_pattern': '1DP', 'seat_positions': [1, 2, 3, 4]},
    bid='2S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'weak_range',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 3,
                   'max': 7,
                   'weight': 60},
                  {'criterion_id': 'six_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 6,
                   'weight': 70}]},
    meaning={'nature_labels': ['natural', 'weak'],
     'call_act_types': ['descriptive', 'preemptive'],
     'action_type': 'weak_jump_shift',
     'target_suit': 'S',
     'shown_length_min': 6,
     'alertable': True},
    effects=[{'key': 'weak_jump_shift', 'target_suit': 'S', 'shown_length_min': 6}],
    description='Weak jump-shift response 2S to 1D.',
    system_notes='After 1D, 2S is weak and natural, not Soloway.',
)
