# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '1SP', 'seat_positions': [1, 2]},
    bid='3C',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'constructive_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 7,
                   'max': 9,
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive'],
     'action_type': 'bergen_raise',
     'target_suit': 'S',
     'raise_strength': 'constructive',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'bergen_raise'},
     {'key': 'major_raise', 'suit': 'S', 'raise_type': 'bergen_constructive'}],
    description='Normal Bergen 3C constructive four-card spade raise.',
    system_notes='After 1S, 3C is a constructive four-card Bergen raise.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '1SP', 'seat_positions': [1, 2]},
    bid='3D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'limit_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 10,
                   'max': 12,
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive', 'invitation'],
     'action_type': 'bergen_raise',
     'target_suit': 'S',
     'raise_strength': 'limit',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'bergen_raise'},
     {'key': 'major_raise', 'suit': 'S', 'raise_type': 'bergen_limit'}],
    description='Normal Bergen 3D limit four-card spade raise.',
    system_notes='After 1S, 3D is a limit four-card Bergen raise.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '1SP', 'seat_positions': [1, 2]},
    bid='3S',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'preemptive_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 0,
                   'max': 6,
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['preemptive'],
     'action_type': 'bergen_raise',
     'target_suit': 'S',
     'raise_strength': 'preemptive',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'S', 'source': 'bergen_raise'},
     {'key': 'major_raise', 'suit': 'S', 'raise_type': 'bergen_preemptive'}],
    description='Normal Bergen 3S preemptive four-card spade raise.',
    system_notes='After 1S, 3S is a preemptive four-card Bergen raise.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '1HP', 'seat_positions': [1, 2]},
    bid='3C',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'constructive_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 7,
                   'max': 9,
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive'],
     'action_type': 'bergen_raise',
     'target_suit': 'H',
     'raise_strength': 'constructive',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'bergen_raise'},
     {'key': 'major_raise', 'suit': 'H', 'raise_type': 'bergen_constructive'}],
    description='Normal Bergen 3C constructive four-card heart raise.',
    system_notes='After 1H, 3C is a constructive four-card Bergen raise.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '1HP', 'seat_positions': [1, 2]},
    bid='3D',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'limit_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 10,
                   'max': 12,
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['descriptive', 'invitation'],
     'action_type': 'bergen_raise',
     'target_suit': 'H',
     'raise_strength': 'limit',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'bergen_raise'},
     {'key': 'major_raise', 'suit': 'H', 'raise_type': 'bergen_limit'}],
    description='Normal Bergen 3D limit four-card heart raise.',
    system_notes='After 1H, 3D is a limit four-card Bergen raise.',
)

Call(
    id='cs_6',
    context={'auction_pattern': '1HP', 'seat_positions': [1, 2]},
    bid='3H',
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'four_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 4,
                   'weight': 50},
                  {'criterion_id': 'preemptive_values',
                   'evaluator': 'range_contains',
                   'input': 'self.hcp',
                   'min': 0,
                   'max': 6,
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['preemptive'],
     'action_type': 'bergen_raise',
     'target_suit': 'H',
     'raise_strength': 'preemptive',
     'alertable': True},
    effects=[{'key': 'agreed_suit', 'suit': 'H', 'source': 'bergen_raise'},
     {'key': 'major_raise', 'suit': 'H', 'raise_type': 'bergen_preemptive'}],
    description='Normal Bergen 3H preemptive four-card heart raise.',
    system_notes='After 1H, 3H is a preemptive four-card Bergen raise.',
)
