# BSL source for Partner bidding agreements.
# Edit this file as the source of truth for this Gadget object set.

Call(
    id='cs_1',
    context={'auction_pattern': '*'},
    bid='4N',
    requires={'all': [{'state_exists': {'key': 'agreed_suit'}},
             {'not': {'state_exists': {'key': 'keycard_context', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'strong_slam_values',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 18,
                   'weight': 80},
                  {'criterion_id': 'agreed_suit_length',
                   'evaluator': 'expression',
                   'expr': {'op': 'gte',
                            'left': {'op': 'length',
                                     'hand': 'self',
                                     'suit': {'op': 'state_attribute',
                                              'query': {'key': 'agreed_suit'},
                                              'attribute': 'suit'}},
                            'right': {'const': 5}},
                   'weight': 40}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry', 'keycard_asking'],
     'action_type': 'rkcb_1430',
     'target_suit_source': 'agreed_suit',
     'alertable': True},
    capabilities=['start_frame', 'keycard_ask', 'slam_inquiry'],
    effects=[{'key': 'keycard_context',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'agreed_suit'},
                              'attribute': 'suit'}},
      'ask_call': '4N',
      'method': '1430',
      'status': 'pending'}],
    description='Asker bids 4N as RKCB 1430 for the currently agreed suit.',
    system_notes='When a suit is agreed and slam interest is present, 4N is RKCB 1430 for that suit.',
)

Call(
    id='cs_2',
    context={'auction_pattern': '*'},
    bid=StepAfterState('keycard_context', method='1430', status='pending', step=1),
    requires={'all': [{'state_exists': {'key': 'keycard_context', 'method': '1430', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': '1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'one_or_four_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'in',
                            'left': {'op': 'keycard_count',
                                     'hand': 'self',
                                     'trump_suit': {'op': 'state_attribute',
                                                    'query': {'key': 'keycard_context',
                                                              'method': '1430',
                                                              'status': 'pending'},
                                                    'attribute': 'trump_suit'}},
                            'right': {'const': [1, 4]}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_range': [1, 4],
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'keycard_context',
                                        'method': '1430',
                                        'status': 'pending'},
                              'attribute': 'trump_suit'}},
      'method': '1430',
      'response': 'one_or_four'}],
    description='Responder to RKCB answers 5C, showing 1 or 4 keycards.',
    system_notes='In RKCB 1430, 5C shows 1 or 4 keycards.',
)

Call(
    id='cs_3',
    context={'auction_pattern': '*'},
    bid=StepAfterState('keycard_context', method='1430', status='pending', step=2),
    requires={'all': [{'state_exists': {'key': 'keycard_context', 'method': '1430', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': '1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'zero_or_three_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'in',
                            'left': {'op': 'keycard_count',
                                     'hand': 'self',
                                     'trump_suit': {'op': 'state_attribute',
                                                    'query': {'key': 'keycard_context',
                                                              'method': '1430',
                                                              'status': 'pending'},
                                                    'attribute': 'trump_suit'}},
                            'right': {'const': [0, 3]}},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_range': [0, 3],
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'keycard_context',
                                        'method': '1430',
                                        'status': 'pending'},
                              'attribute': 'trump_suit'}},
      'method': '1430',
      'response': 'zero_or_three'}],
    description='Responder to RKCB answers 5D, showing 0 or 3 keycards.',
    system_notes='In RKCB 1430, 5D shows 0 or 3 keycards.',
)

Call(
    id='cs_4',
    context={'auction_pattern': '*'},
    bid=StepAfterState('keycard_context', method='1430', status='pending', step=3),
    requires={'all': [{'state_exists': {'key': 'keycard_context', 'method': '1430', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': '1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'two_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'keycard_count',
                                     'hand': 'self',
                                     'trump_suit': {'op': 'state_attribute',
                                                    'query': {'key': 'keycard_context',
                                                              'method': '1430',
                                                              'status': 'pending'},
                                                    'attribute': 'trump_suit'}},
                            'right': {'const': 2}},
                   'weight': 100},
                  {'criterion_id': 'lacks_trump_queen',
                   'evaluator': 'expression',
                   'expr': {'op': 'not',
                            'arg': {'op': 'contains_rank',
                                    'hand': 'self',
                                    'suit': {'op': 'state_attribute',
                                             'query': {'key': 'keycard_context',
                                                       'method': '1430',
                                                       'status': 'pending'},
                                             'attribute': 'trump_suit'},
                                    'rank': 'Q'}},
                   'weight': 20}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_count': 2,
     'trump_queen': False,
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'keycard_context',
                                        'method': '1430',
                                        'status': 'pending'},
                              'attribute': 'trump_suit'}},
      'method': '1430',
      'response': 'two_without_queen'}],
    description='Responder to RKCB answers 5H, showing 2 keycards without the trump queen.',
    system_notes='In RKCB 1430, 5H shows 2 keycards without the trump queen.',
)

Call(
    id='cs_5',
    context={'auction_pattern': '*'},
    bid=StepAfterState('keycard_context', method='1430', status='pending', step=4),
    requires={'all': [{'state_exists': {'key': 'keycard_context', 'method': '1430', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'keycard_response', 'method': '1430'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'two_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'keycard_count',
                                     'hand': 'self',
                                     'trump_suit': {'op': 'state_attribute',
                                                    'query': {'key': 'keycard_context',
                                                              'method': '1430',
                                                              'status': 'pending'},
                                                    'attribute': 'trump_suit'}},
                            'right': {'const': 2}},
                   'weight': 100},
                  {'criterion_id': 'has_trump_queen',
                   'evaluator': 'expression',
                   'expr': {'op': 'contains_rank',
                            'hand': 'self',
                            'suit': {'op': 'state_attribute',
                                     'query': {'key': 'keycard_context',
                                               'method': '1430',
                                               'status': 'pending'},
                                     'attribute': 'trump_suit'},
                            'rank': 'Q'},
                   'weight': 20}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response'],
     'action_type': 'keycard_response',
     'keycard_count': 2,
     'trump_queen': True,
     'alertable': True},
    capabilities=['answer_frame', 'keycard_response'],
    effects=[{'key': 'keycard_response',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'keycard_context',
                                        'method': '1430',
                                        'status': 'pending'},
                              'attribute': 'trump_suit'}},
      'method': '1430',
      'response': 'two_with_queen'}],
    description='Responder to RKCB answers 5S, showing 2 keycards with the trump queen.',
    system_notes='In RKCB 1430, 5S shows 2 keycards with the trump queen.',
)

Call(
    id='cs_6',
    context={'auction_pattern': '*'},
    bid='5N',
    requires={'all': [{'state_exists': {'key': 'keycard_response',
                              'method': '1430',
                              'response': 'one_or_four'}},
             {'not': {'state_exists': {'key': 'specific_king_ask', 'status': 'pending'}}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'asker_has_four_keycards',
                   'evaluator': 'expression',
                   'expr': {'op': 'eq',
                            'left': {'op': 'keycard_count',
                                     'hand': 'self',
                                     'trump_suit': {'op': 'state_attribute',
                                                    'query': {'key': 'keycard_response',
                                                              'method': '1430'},
                                                    'attribute': 'trump_suit'}},
                            'right': {'const': 4}},
                   'weight': 100},
                  {'criterion_id': 'trump_queen_available',
                   'evaluator': 'expression',
                   'expr': {'op': 'contains_rank',
                            'hand': 'self',
                            'suit': {'op': 'state_attribute',
                                     'query': {'key': 'keycard_response', 'method': '1430'},
                                     'attribute': 'trump_suit'},
                            'rank': 'Q'},
                   'weight': 20}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['inquiry'],
     'action_type': 'specific_king_ask',
     'alertable': True},
    capabilities=['start_frame', 'specific_king_ask', 'slam_inquiry'],
    effects=[{'key': 'all_keycards_known',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'keycard_response', 'method': '1430'},
                              'attribute': 'trump_suit'}},
      'status': 'yes'},
     {'key': 'specific_king_ask',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'keycard_response', 'method': '1430'},
                              'attribute': 'trump_suit'}},
      'status': 'pending'}],
    description='Asker bids 5N to ask for specific kings after accounting for all keycards.',
    system_notes='5N asks for specific kings and guarantees all keycards in this benchmark route.',
)

Call(
    id='cs_7',
    context={'auction_pattern': '*'},
    bid='6D',
    requires={'all': [{'state_exists': {'key': 'specific_king_ask', 'status': 'pending'}},
             {'not': {'state_exists': {'key': 'specific_king_response'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'has_diamond_king',
                   'evaluator': 'expression',
                   'expr': {'op': 'contains_rank', 'hand': 'self', 'suit': 'D', 'rank': 'K'},
                   'weight': 100}]},
    meaning={'nature_labels': ['artificial', 'conventional'],
     'call_act_types': ['relay_response', 'control_showing'],
     'action_type': 'specific_king_response',
     'target_suit': 'D',
     'alertable': True},
    capabilities=['answer_frame', 'specific_king_response'],
    effects=[{'key': 'specific_king_response',
      'trump_suit': {'expr': {'op': 'state_attribute',
                              'query': {'key': 'specific_king_ask', 'status': 'pending'},
                              'attribute': 'trump_suit'}},
      'target_suit': 'D',
      'rank': 'K'}],
    description='Responder shows the diamond king over the specific-king ask.',
    system_notes='Over 5N specific-king ask, 6D shows the diamond king.',
)

Call(
    id='cs_8',
    context={'auction_pattern': '*'},
    bid='7S',
    requires={'all': [{'state_exists': {'key': 'all_keycards_known', 'trump_suit': 'S', 'status': 'yes'}},
             {'state_exists': {'key': 'specific_king_response',
                              'trump_suit': 'S',
                              'target_suit': 'D',
                              'rank': 'K'}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'final_grand_strength',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 18,
                   'weight': 100},
                  {'criterion_id': 'six_spades',
                   'evaluator': 'min_value',
                   'input': 'self.spades',
                   'min': 6,
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'S',
     'level': 7,
     'alertable': False},
    capabilities=['place_contract', 'slam_placement'],
    effects=[{'key': 'final_contract', 'target_suit': 'S', 'level': 7, 'source': 'rkcb_1430'}],
    description='Asker places the grand slam in spades after the diamond king is shown.',
    system_notes='7S is final placement after the RKCB and specific-king route.',
)

Call(
    id='cs_9',
    context={'auction_pattern': '*'},
    bid='7H',
    requires={'all': [{'state_exists': {'key': 'all_keycards_known', 'trump_suit': 'H', 'status': 'yes'}},
             {'state_exists': {'key': 'specific_king_response',
                              'trump_suit': 'H',
                              'target_suit': 'D',
                              'rank': 'K'}},
             {'not': {'state_exists': {'key': 'final_contract'}}}]},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'final_grand_strength',
                   'evaluator': 'min_value',
                   'input': 'self.hcp',
                   'min': 18,
                   'weight': 100},
                  {'criterion_id': 'six_hearts',
                   'evaluator': 'min_value',
                   'input': 'self.hearts',
                   'min': 6,
                   'weight': 20}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['final_placement'],
     'action_type': 'place_contract',
     'target_suit': 'H',
     'level': 7,
     'alertable': False},
    capabilities=['place_contract', 'slam_placement'],
    effects=[{'key': 'final_contract', 'target_suit': 'H', 'level': 7, 'source': 'rkcb_1430'}],
    description='Asker places the grand slam in hearts after the diamond king is shown.',
    system_notes='7H is final placement after the RKCB and specific-king route.',
)

Call(
    id='cs_10',
    context={'auction_pattern': '*'},
    bid='P',
    requires={'state_exists': {'key': 'final_contract', 'source': 'rkcb_1430'}},
    selection={'algorithm': 'weighted_score',
     'criteria': [{'criterion_id': 'final_contract_placed',
                   'evaluator': 'state_exists',
                   'query': {'key': 'final_contract', 'source': 'rkcb_1430'},
                   'weight': 100}]},
    meaning={'nature_labels': ['natural'],
     'call_act_types': ['final_placement'],
     'action_type': 'pass_final_contract',
     'alertable': False},
    capabilities=['place_contract', 'pass_final_contract'],
    description='Partner passes after a final contract has been placed.',
    system_notes='After a final contract is placed, partner passes to end the auction.',
)
